<?php

namespace Database\Seeders;

use App\Models\Staff;
use App\Models\StaffPayout;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class StaffPayoutDemoSeeder extends Seeder
{
    public function run(): void
    {
        $staffMembers = Staff::select('id')->take(3)->get(); // Limit to 3 staff members
        if ($staffMembers->isEmpty()) {
            return;
        }

        $today = Carbon::today();

        foreach ($staffMembers as $staff) {
            // Create 3 payouts per staff: last month, this month, and pending next month
            $periods = [
                ['date' => $today->copy()->subMonth()->endOfMonth(), 'status' => 'Paid', 'amount' => rand(3000, 7000)],
                ['date' => $today->copy()->endOfMonth(), 'status' => 'Processing', 'amount' => rand(3000, 7000)],
                ['date' => $today->copy()->addMonth()->endOfMonth(), 'status' => 'Planned', 'amount' => rand(3000, 7000)],
            ];

            foreach ($periods as $p) {
                StaffPayout::updateOrCreate(
                    [
                        'staff_id' => $staff->id,
                        'payout_date' => $p['date']->format('Y-m-d'),
                    ],
                    [
                        'total_amount' => $p['amount'],
                        'status' => $p['status'],
                        'notes' => 'Demo payout generated by StaffPayoutDemoSeeder',
                    ]
                );
            }
        }
    }
}
