services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - .dockerignore
        - render.yaml
        - app/**
        - bootstrap/**
        - config/**
        - database/**
        - public/**
        - resources/**
        - routes/**
        - storage/**
        - composer.json
        - composer.lock
        - package.json
        - package-lock.json
        - vite.config.js # Ensure this is present if you use Vite
        - .env.example
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1snd5mmcj7s73e8kfmg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: healthcare_db_i729
      - key: DB_USERNAME
        value: healthcare_db_i729_user
      - key: DB_PASSWORD
        value: HCxz1wUe6zb6u8Qkncp91k6IR0hGy33P
      # --- NEW ENV VARS FOR MIXED CONTENT FIX ---
      - key: APP_URL
        value: https://gerayehealthcare-1.onrender.com # IMPORTANT: Use your actual Render URL here
      - key: TRUSTED_PROXIES
        value: "*" # Tells Laravel to trust proxy headers for HTTPS detection