export function useClinicInfo() {
  const getClinicName = (): string => {
    // Try window config, then meta tag, then fallback
    // @ts-ignore
    const fromWindow = (typeof window !== 'undefined' && window.AppConfig && window.AppConfig.clinicName) ? window.AppConfig.clinicName : null;
    if (fromWindow) return String(fromWindow);

    const meta = typeof document !== 'undefined' ? document.querySelector('meta[name="clinic-name"]') as HTMLMetaElement | null : null;
    if (meta?.content) return meta.content;

    return 'Geraye Healthcare';
  };

  const getClinicLogo = (): string => {
    // @ts-ignore
    const fromWindow = (typeof window !== 'undefined' && window.AppConfig && window.AppConfig.clinicLogo) ? window.AppConfig.clinicLogo : null;
    if (fromWindow) return String(fromWindow);

    const meta = typeof document !== 'undefined' ? document.querySelector('meta[name="clinic-logo"]') as HTMLMetaElement | null : null;
    if (meta?.content) return meta.content;

    return '/images/geraye_logo.jpeg';
  };

  const getPrintFooterText = (): string => {
    const clinic = getClinicName();
    const ts = new Date().toLocaleString();
    return `Generated by ${clinic} • ${ts}`;
  };

  return { getClinicName, getClinicLogo, getPrintFooterText };
}
