<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Patient;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Inertia\Inertia;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth; // <-- Import Auth facade for getting logged in user

class PatientController extends Controller
{
    public function index(Request $request): \Inertia\Response
    {
        $query = Patient::query();

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where('full_name', 'ilike', "%{$search}%")
                  ->orWhere('email', 'ilike', "%{$search}%");
        }

        // --- FIX: Robust sorting parameter handling ---
        if ($request->filled('sort') && !empty($request->input('sort'))) {
            $query->orderBy($request->input('sort'), $request->input('direction', 'asc'));
        } else {
            // Default sort if no valid 'sort' parameter is provided
            $query->orderBy('created_at', 'desc');
        }
        // --- END FIX ---

        $patients = $query->paginate($request->input('per_page', 10))->withQueryString();

        return Inertia::render('Admin/Patients/Index', [
            'patients' => $patients,
            'filters' => $request->only(['search', 'sort', 'direction', 'per_page']),
        ]);
    }

    public function create()
    {
        return Inertia::render('Admin/Patients/Create');
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'full_name' => 'required|string|max:255',
            'fayda_id' => 'nullable|string|max:255|unique:patients,fayda_id',
            'date_of_birth' => 'required|date',
            'gender' => 'nullable|string|max:10',
            'address' => 'nullable|string',
            'phone_number' => 'nullable|string|regex:/^[0-9+\-\s\(\)]+$/|max:255', // Removed unique validation
            'email' => 'nullable|email:rfc,dns|max:255', // Validation for email
            'emergency_contact' => 'nullable|string',
            'source' => 'nullable|string|max:255|in:TikTok,Website,Referral,Walk-in',
            'geolocation' => 'nullable|string',
            // patient_code is generated by the model's booted method, not from request
        ]);

        // --- NEW FEATURE: Assign the logged-in user as the registrant ---
        // This assumes the logged-in user is a 'staff' member.
        // Adjust this logic if different user types register patients (e.g., Auth::guard('caregiver')->check())
        if (Auth::check()) {
            $user = Auth::user();
            // Directly find the staff member associated with the logged-in user's ID
            $staffMember = \App\Models\Staff::where('user_id', $user->id)->first();

            if ($staffMember) {
                $data['registered_by_staff_id'] = $staffMember->id;
            }
            // If you also need to handle caregivers, you would add similar logic here
            // For example, if a caregiver is also a user and has a caregiver profile:
            // if ($user->caregiver) {
            //     $data['registered_by_caregiver_id'] = $user->caregiver->id;
            // }
        }
        // --- END NEW FEATURE ---

        Patient::create($data);

        return redirect()->route('admin.patients.index')->with('success', 'Patient created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Patient $patient)
    {
        // Eager load the relationships needed for the 'registered by' display
        // and ensure accessors like 'age' are available.
        $patient->load(['registeredByStaff']);

        return Inertia::render('Admin/Patients/Show', [
            'patient' => $patient,
        ]);
    }

    public function edit(Patient $patient)
    {
        return Inertia::render('Admin/Patients/Edit', [
            'patient' => $patient,
        ]);
    }

     public function update(Request $request, Patient $patient)
    {
        $data = $request->validate([
            'full_name' => 'required|string|max:255',
            'fayda_id' => ['nullable', 'string', 'max:255', Rule::unique('patients')->ignore($patient->id)],
            'date_of_birth' => 'required|date',
            'gender' => 'nullable|string|max:10',
            'address' => 'nullable|string',
            'phone_number' => 'nullable|string|regex:/^[0-9+\-\s\(\)]+$/|max:255', // Removed unique validation
            'email' => 'nullable|email:rfc,dns|max:255', // Validation for email
            'emergency_contact' => 'nullable|string',
            'source' => 'nullable|string|max:255|in:TikTok,Website,Referral,Walk-in',
            'geolocation' => 'nullable|string',
        ]);

        // Note: For update, 'registered_by_staff_id' is typically not updated here,
        // as it represents the initial registrant. If you need to change it,
        // you'd add validation and a field to your edit form.

        $patient->update($data);

        return redirect()->route('admin.patients.index')->with('success', 'Patient updated successfully.');
    }

    public function destroy(Patient $patient)
    {
        $patient->delete();
        return back()->with('success', 'Patient deleted successfully.');
    }

    public function export(Request $request)
    {
        $type = $request->get('type');
        // Include 'email' and 'fayda_id' in select statement for exports if needed
        $patients = Patient::select('full_name', 'patient_code', 'fayda_id', 'email', 'source', 'phone_number', 'address', 'gender', 'emergency_contact')->get();

        if ($type === 'csv') {
            $csvData = "Full Name,Patient Code,Fayda ID,Email,Source,Phone,Address,Gender,Emergency Contact\n";
            foreach ($patients as $p) {
                // Ensure values are properly quoted for CSV
                $csvData .= "\"{$p->full_name}\",\"{$p->patient_code}\",\"{$p->fayda_id}\",\"{$p->email}\",\"{$p->source}\",\"{$p->phone_number}\",\"{$p->address}\",\"{$p->gender}\",\"{$p->emergency_contact}\"\n";
            }

            return Response::make($csvData, 200, [
                'Content-Type' => 'text/csv',
                'Content-Disposition' => 'attachment; filename="patients.csv"',
            ]);
        }

        if ($type === 'pdf') {
            // You might need to update your pdf.patients blade view to include new fields
            $pdf = Pdf::loadView('pdf.patients', ['patients' => $patients])->setPaper('a4', 'landscape');
            return $pdf->stream('patients.pdf');
        }

        return abort(400, 'Invalid export type');
    }

    public function printSingle(Patient $patient)
    {
        // For single patient print, eager load relationships if you display who registered them
        $patient->load(['registeredByStaff', 'registeredByCaregiver']);
        $pdf = Pdf::loadView('pdf.patient-single', ['patient' => $patient])->setPaper('a4', 'portrait');
        return $pdf->stream("patient-{$patient->patient_code}.pdf");
    }
    public function printCurrent(Request $request)
    {
        $query = Patient::query();

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where('full_name', 'ilike', "%{$search}%")
                  ->orWhere('email', 'ilike', "%{$search}%");
        }

        if ($request->filled('sort') && !empty($request->input('sort'))) {
            $query->orderBy($request->input('sort'), $request->input('direction', 'asc'));
        } else {
            $query->orderBy('created_at', 'desc');
        }

        $patients = $query->paginate($request->input('per_page', 10), ['*'], 'page', $request->input('page', 1));

        $pdf = Pdf::loadView('pdf.patients-current', ['patients' => $patients])->setPaper('a4', 'landscape');
        return $pdf->stream('patients-current.pdf');
    }

    public function printAll(Request $request)
    {
        $patients = Patient::orderBy('full_name')->get(); // Fetch all patients, ordered

        // Render a dedicated Inertia component for printing all data
        // This component will be similar to your Index.vue but optimized for print,
        // perhaps without pagination controls or search bars.
        return Inertia::render('Admin/Patients/PrintAll', [
            'patients' => $patients,
        ]);
    }
}
