// This file is auto-generated by Ziggy
// It provides type-safe route helpers for the application

// In a typical Ziggy setup, these would be auto-generated
// For now, we'll provide basic implementations that use the route() helper

export function home() {
    return route('home');
}

export function dashboard() {
    return route('dashboard');
}

export function login() {
    return route('login');
}

export function register() {
    return route('register');
}

export function logout() {
    return route('logout');
}

// Re-export from other route files
export * from './profile';
export * from './password';
export * from './verification';
export * from './appearance';
export * from './quotes';